include styles/

./: styles/

# This alias presents a single target that depends on all of the plugins
# loaded by libs{Qt5Widgets} for a specific platform.
#
alias{Qt5WidgetsPlugins}: styles/libs{qmacstyle}: include = $macos
alias{Qt5WidgetsPlugins}: styles/libs{qwindowsvistastyle}: include = $windows
