include imageformats/
include platforminputcontexts/
include platforms/

./: imageformats/ platforminputcontexts/ platforms/

# This alias presents a single target that depends on all of the plugins
# loaded by libs{Qt5Gui} for a specific platform.
#
alias{Qt5GuiPlugins}: imageformats/libs{qgif qico qjpeg}

alias{Qt5GuiPlugins}:                                                 \
  platforms/libs{qxcb}                                                \
  platforminputcontexts/libs{composeplatforminputcontextplugin}:      \
    include = ($linux || $bsd)

alias{Qt5GuiPlugins}: platforms/libs{qcocoa}: include = $macos
alias{Qt5GuiPlugins}: platforms/libs{qwindows}: include = $windows
