./: imageformats/ platforminputcontexts/ platforms/ \
    lib{Qt5GuiPluginsMeta}

include imageformats/
include platforminputcontexts/
include platforms/

# This library presents a single target that depends on all of the plugins
# used by libQt5Gui.
#
[rule_hint=cxx] lib{Qt5GuiPluginsMeta}:

lib{Qt5GuiPluginsMeta}: imageformats/libs{qgif qico qjpeg}: \
  include = adhoc

lib{Qt5GuiPluginsMeta}:                                                 \
  platforms/libs{qxcb}                                                  \
  platforminputcontexts/libs{composeplatforminputcontextplugin}:        \
    include = ($linux || $bsd ? adhoc : false)

lib{Qt5GuiPluginsMeta}: platforms/libs{qcocoa}: \
  include = ($macos ? adhoc : false)

lib{Qt5GuiPluginsMeta}: platforms/libs{qwindows}: \
  include = ($windows ? adhoc : false)

hxx{*}: install = false
