# Note: if anything in this file seems underdocumented it is probably covered
#       in libQt5Core/QtCore/buildfile.
#

import impl_libs  = libQt5Core%lib{Qt5Core}
import impl_libs += libQt5Gui%lib{Qt5Gui}

import impl_libs_jpeg = libjpeg-turbo%lib{jpeg}

import! [metadata] moc = Qt5Moc%exe{qt5moc}

./: lib{qgif}:  gif/hxx{main qgifhandler_p} \
                gif/cxx{main qgifhandler}
./: lib{qico}:  ico/hxx{main qicohandler} \
                ico/cxx{main qicohandler}
./: lib{qjpeg}: jpeg/hxx{main qjpeghandler_p}   \
                jpeg/cxx{main qjpeghandler}     \
                $impl_libs_jpeg

lib{qgif qico qjpeg}: $src_root/plugins/hxx{mkspecs/**}

# Plugin metadata files.
#
lib{qgif}: gif/file{gif.json}
lib{qico}: ico/file{ico.json}
lib{qjpeg}: jpeg/file{jpeg.json}

# The "metadata library": its purpose is to make sure all the imported
# libraries are resolved for the moc ad hoc rules below.
#
# Note: use a rule hint to resolve ambiguity between C and C++ library.
#
[rule_hint=cxx] libul{Qt5PluginsImageFormatsMeta}: $impl_libs

lib{qgif qico qjpeg}: libul{Qt5PluginsImageFormatsMeta}

# Dependencies involving moc_main.cpp and main.cpp (from which it is
# generated).
#
lib{qgif}:  gif/cxx{moc_main}:  include = adhoc
lib{qico}:  ico/cxx{moc_main}:  include = adhoc
lib{qjpeg}: jpeg/cxx{moc_main}: include = adhoc

gif/cxx{moc_main}:  gif/hxx{main}
ico/cxx{moc_main}:  ico/hxx{main}
jpeg/cxx{moc_main}: jpeg/hxx{main}

# moc_main.cpp needs to be compiled.
#
lib{qgif}:  gif/cxx{moc_main}
lib{qico}:  ico/cxx{moc_main}
lib{qjpeg}: jpeg/cxx{moc_main}

hxx{moc_predefs}: $src_root/plugins/mkspecs/features/data/cxx{dummy}
%
if ($cxx.id != 'msvc')
{{
  diag gen ($>[0])
  $cxx.path $cc.poptions $cxx.poptions $cc.coptions $cxx.coptions $cxx.mode \
            -o $path($>) -dM -E $path($<)
}}
else
{{
  diag gen ($>[0])
  cat <<EOI >$path($>)
  #define _WIN32
  #define WIN32
  EOI
}}

# -I options for the system header directories.
#
sys_incl = $regex.apply($cxx.sys_hdr_dirs, '(.+)', '-I\1')

# Rule to run moc on a header file.
#
# Use -f to override the path moc uses to #include the input file, which is
# relative to the output directory, with just the name of the input file.
#
# Note that we depend on libul{Qt5PluginsImageFormatsMeta} in order to ensure
# all the imported libraries are resolved for these ad hoc rules.
#
# Also add QtCore's and QtGui's exported header search directories (via
# libul{Qt5PluginsImageFormatsMeta}) otherwise certain definitions required by
# moc will be missing.
#
# Note that hxx{moc_predefs} must always be in position 1.
#
cxx{~'/moc_(.*)/'}: hxx{~'/\1/'} hxx{moc_predefs} libul{Qt5PluginsImageFormatsMeta} $moc
{{
  o = $path($>[0])
  t = $(o).t

  dep_incl = $cxx.lib_poptions(libul{Qt5PluginsImageFormatsMeta})
  depdb hash $dep_incl

  # Note: exclude libul{Qt5PluginsImageFormatsMeta} from update during match
  #       not to mess up its for-install'ness.
  #
  depdb dyndep                                                  \
    --byproduct --drop-cycles --what=header --default-type=h    \
    --update-exclude libul{Qt5PluginsImageFormatsMeta}          \
    --file $t

  diag moc ($<[0])

  s = $path($<[0])

  $moc --include $path($<[1]) $cc.poptions $cxx.poptions $dep_incl $sys_incl \
    -f $leaf($s) --output-dep-file --dep-file-path $t -o $o $s
}}

# Rule to run moc on a source file.
#
# See the header-input moc rule regarding the header prerequisites.
#
moc{~'/(.*)/'}: cxx{~'/\1/'} hxx{moc_predefs} libul{Qt5PluginsImageFormatsMeta} $moc
{{
  o = $path($>[0])
  t = $(o).t

  dep_incl = $cxx.lib_poptions(libul{Qt5PluginsImageFormatsMeta})
  depdb hash $dep_incl

  # Note: exclude libul{Qt5PluginsImageFormatsMeta} from update during match
  #       not to mess up its for-install'ness.
  #
  depdb dyndep                                                  \
    --byproduct --drop-cycles --what=header --default-type=h    \
    --update-exclude libul{Qt5PluginsImageFormatsMeta}          \
    --file $t

  diag moc ($<[0])

  s = $path($<[0])

  $moc --include $path($<[1]) $cc.poptions $cxx.poptions $dep_incl $sys_incl \
    --output-dep-file --dep-file-path $t -o $o $s
}}

# Build options.
#

cxx.poptions += -DQT_CORE_LIB                                   \
                -DQT_DEPRECATED_WARNINGS                        \
                -DQT_GUI_LIB                                    \
                -DQT_NO_DEBUG                                   \
                -DQT_NO_JAVA_STYLE_ITERATORS                    \
                -DQT_NO_LINKED_LIST                             \
                -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT        \
                -DQT_PLUGIN

if ($cxx.target.class  != 'windows')
{
  cxx.poptions += -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE
}

# Disable exceptions and don't export any symbols (see Qt5Plugins/README-DEV).
#
cxx.poptions += -DQT_NO_EXCEPTIONS

switch $cxx.class
{
  case 'gcc'
    cxx.coptions += -fno-exceptions \
                    -fvisibility=hidden -fvisibility-inlines-hidden
  case 'msvc'
    cxx.coptions += /EHs- /EHc-
}

# Every directory under mkspecs/ contains a unique `qplatformdefs.h`.
#
# Note that Mac OS with GCC is not supported by upstream (see README-DEV for
# details).
#
switch $cxx.target.class, $cxx.id, $cxx.target.system
{
  case 'linux', 'gcc'
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/linux-g++"
  case 'linux', 'clang'
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/linux-clang"
  case 'macos', 'clang-apple'
  {
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/macx-clang"

    # lib{Qt5Gui}: cxx.libs += -framework AppKit  \
    #                          -framework Foundation
                             # -framework CoreGraphics
  }
  case 'bsd', 'clang', 'freebsd'
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/freebsd-clang"
  case 'bsd', 'gcc', 'openbsd'
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/openbsd-g++"
  case 'bsd', 'gcc', 'netbsd'
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/netbsd-g++"
  case 'windows', 'msvc'
  {
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/win32-msvc"
    cxx.poptions += -D_ENABLE_EXTENDED_ALIGNED_STORAGE

    # lib{Qt5Gui}: cxx.libs += ole32.lib advapi32.lib shell32.lib
  }
  case 'windows', 'msvc-clang' | 'clang'
  {
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/win32-clang-msvc"
    cxx.poptions += -D_ENABLE_EXTENDED_ALIGNED_STORAGE

    # lib{Qt5Gui}: cxx.libs += ole32.lib advapi32.lib shell32.lib
  }
  case 'windows', 'gcc', 'mingw32'
  {
    cxx.poptions =+ "-I$src_root/plugins/mkspecs/win32-g++"
    cxx.poptions +=  -DMINGW_HAS_SECURE_API=1

    # lib{Qt5Gui}: cxx.libs += -lole32 -ladvapi32 -lshell32
  }
}

gif/obj{main qgifhandler} gif/obj{moc_main}: \
  cxx.poptions =+ "-I$out_base/gif" "-I$src_base/gif"
ico/obj{main qicohandler} ico/obj{moc_main}: \
  cxx.poptions =+ "-I$out_base/ico" "-I$src_base/ico"
jpeg/obj{main qjpeghandler} jpeg/obj{moc_main}: \
  cxx.poptions =+ "-I$out_base/jpeg" "-I$src_base/jpeg"

if ($cxx.target.class != 'windows')
{
  lib{qgif qico qjpeg}: cxx.libs += -pthread
}

lib{qgif qico qjpeg}: install = lib/qt5/plugins/imageformats/

hxx{*}: install = false
