intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{Qt5Widgets}: {hxx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
out_pfx = [dir_path] $out_root/QtWidgets/
src_pfx = [dir_path] $src_root/QtWidgets/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

{hbmia obja}{*}: cxx.poptions += -DLIBQT5WIDGETS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBQT5WIDGETS_SHARED_BUILD

# Export options.
#
lib{Qt5Widgets}:
{
  cxx.export.poptions = "-I$out_pfx" "-I$src_pfx"
  cxx.export.libs = $intf_libs
}

liba{Qt5Widgets}: cxx.export.poptions += -DLIBQT5WIDGETS_STATIC
libs{Qt5Widgets}: cxx.export.poptions += -DLIBQT5WIDGETS_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{Qt5Widgets}: bin.lib.version = "-$version.project_id"
else
  lib{Qt5Widgets}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libQt5Widgets/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/libQt5Widgets/
  install.subdirs = true
}
