import libs = libQt5Gui%lib{Qt5Gui}

import! [metadata] moc = Qt5Moc%exe{qt5moc}

exe{gui-app}: hxx{rasterwindow} cxx{gui-app}
{
  # Close the window automatically after a few seconds.
  #
  test.options = --auto-close
}

exe{gui-app}:          cxx{moc_rasterwindow}: include = adhoc
cxx{moc_rasterwindow}: hxx{rasterwindow}

# The "metadata libraries": its purpose is to make sure all the imported
# libraries are resolved for the ad hoc moc rules below.
#
# Note: use a rule hint to resolve ambiguity between C and C++ library.
#
[rule_hint=cxx] libue{Qt5GuiTestsMeta}: $libs

import corelib = libQt5Core%lib{Qt5Core}
moc_predefs_path = $($corelib: libQt5Core.moc_predefs_path)

# Rule to run moc on a header file (foo.h -> moc_foo.cpp).
#
# @@ TMP - QtGui would start getting compiled right before rasterwindow.h
#          would get moc'd, so presumably the trigger is this rule's
#          dependency on libue{QtGuiTestsMeta}. After removing this dependency
#          QtGui was no longer being built during match.
#
#        - Disabling the plugins in QtGui doesn't make a difference.
#
#        - Building QtGuiPlugins/platforms/ triggers it at times (so it must
#          be racy), but neither QtGuiPlugins/imageformats/ nor
#          QtGuiPlugins/platforminputs/ appear to trigger it.
#
cxx{~'/moc_(.*)/'}: hxx{~'/\1/'} libue{Qt5GuiTestsMeta} $moc
{{
  o = $path($>[0])
  t = $(o).t

  dep_incl = $cxx.lib_poptions(libue{Qt5GuiTestsMeta})

  depdb hash $dep_incl

  # Note: exclude libue{Qt5GuiTestsMeta} from update during match not to mess
  #       up its for-install'ness.
  #
  depdb dyndep                                                  \
    --byproduct --drop-cycles --what=header --default-type=h    \
    --update-exclude libue{Qt5GuiTestsMeta}                     \
    --file $t

  diag moc ($<[0])

  s = $path($<[0])

  sys_incl = $regex.apply($cxx.sys_hdr_dirs, '(.+)', '-I\1')

  # -i: don't include the header (we don't need it and it's simpler this way).
  #
  $moc --include $moc_predefs_path                      \
    $cc.poptions $cxx.poptions $dep_incl $sys_incl      \
    -i --output-dep-file --dep-file-path $t -o $o $s
}}

exe{gui-app}: libue{Qt5GuiTestsMeta}

cxx.poptions =+ "-I$out_base"
