// These are the same contents generated by the upstream build if tracepoints
// are disabled (see
// upstream/qtbase/mkspecs/features/qt_tracepoints.prf).
//
// Note that qtrace_p.h is a private QtCore header.
//
#include <private/qtrace_p.h>
