intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{Qt5Core}: {hxx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DQTCORE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DQTCORE_SHARED_BUILD

# Export options.
#
lib{Qt5Core}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{Qt5Core}: cxx.export.poptions += -DQTCORE_STATIC
libs{Qt5Core}: cxx.export.poptions += -DQTCORE_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{Qt5Core}: bin.lib.version = "-$version.project_id"
else
  lib{Qt5Core}: bin.lib.version = "-$version.major.$version.minor"

# Install into the QtCore/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/QtCore/
  install.subdirs = true
}
